webtalk_init -webtalk_dir D:\\Xilinx_Vivado\\ucos_dma_modified_for_kerone\\ucos_dma.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "ven. juil. 13 09:06:01 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bq7ham44jp7glfda5phqmf0q1h" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1531311422706" -context "sdk\\\\bsp/1531311422706"
webtalk_add_data -client sdk -key hwid -value "1530267207152" -context "sdk\\\\bsp/1531311422706"
webtalk_add_data -client sdk -key os -value "ucos" -context "sdk\\\\bsp/1531311422706"
webtalk_add_data -client sdk -key apptemplate -value "helloworld_osii" -context "sdk\\\\bsp/1531311422706"
webtalk_add_data -client sdk -key uid -value "1531311425641" -context "sdk\\\\application/1531311425641"
webtalk_add_data -client sdk -key hwid -value "1530267207152" -context "sdk\\\\application/1531311425641"
webtalk_add_data -client sdk -key bspid -value "1531311422706" -context "sdk\\\\application/1531311425641"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1531311425641"
webtalk_add_data -client sdk -key os -value "ucos" -context "sdk\\\\application/1531311425641"
webtalk_add_data -client sdk -key apptemplate -value "helloworld_osii" -context "sdk\\\\application/1531311425641"
webtalk_add_data -client sdk -key uid -value "1531312090541" -context "sdk\\\\bsp/1531312090541"
webtalk_add_data -client sdk -key hwid -value "1530267207152" -context "sdk\\\\bsp/1531312090541"
webtalk_add_data -client sdk -key os -value "ucos" -context "sdk\\\\bsp/1531312090541"
webtalk_add_data -client sdk -key apptemplate -value "helloworld_osii" -context "sdk\\\\bsp/1531312090541"
webtalk_add_data -client sdk -key uid -value "1531312093166" -context "sdk\\\\application/1531312093166"
webtalk_add_data -client sdk -key hwid -value "1530267207152" -context "sdk\\\\application/1531312093166"
webtalk_add_data -client sdk -key bspid -value "1531312090541" -context "sdk\\\\application/1531312093166"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1531312093166"
webtalk_add_data -client sdk -key os -value "ucos" -context "sdk\\\\application/1531312093166"
webtalk_add_data -client sdk -key apptemplate -value "helloworld_osii" -context "sdk\\\\application/1531312093166"
webtalk_transmit -clientid 630958138 -regid "" -xml D:\\Xilinx_Vivado\\ucos_dma_modified_for_kerone\\ucos_dma.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Xilinx_Vivado\\ucos_dma_modified_for_kerone\\ucos_dma.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Xilinx_Vivado\\ucos_dma_modified_for_kerone\\ucos_dma.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
