# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
# IP: The module: 'design_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/bd_afc3_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_49/bd_afc3_s01a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_55/bd_afc3_s02a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_59/bd_afc3_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_65/bd_afc3_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_60/bd_afc3_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_61/bd_afc3_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_62/bd_afc3_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_63/bd_afc3_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_64/bd_afc3_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_56/bd_afc3_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_57/bd_afc3_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_58/bd_afc3_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_52/bd_afc3_s02mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_53/bd_afc3_s02tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_54/bd_afc3_s02sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_50/bd_afc3_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_51/bd_afc3_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_46/bd_afc3_s01mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_47/bd_afc3_s01tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_48/bd_afc3_s01sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/bd_afc3_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/bd_afc3_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_40/bd_afc3_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_41/bd_afc3_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_42/bd_afc3_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/bd_afc3_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/bd_afc3_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/bd_afc3_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/bd_afc3_s00a2s_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_49/bd_afc3_s01a2s_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_55/bd_afc3_s02a2s_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_59/bd_afc3_m00s2a_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_60/bd_afc3_m00arn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_61/bd_afc3_m00rn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_62/bd_afc3_m00awn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_63/bd_afc3_m00wn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_64/bd_afc3_m00bn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_56/bd_afc3_sawn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_57/bd_afc3_swn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_58/bd_afc3_sbn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_50/bd_afc3_sarn_3_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_51/bd_afc3_srn_3_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/bd_afc3_sarn_2_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/bd_afc3_srn_2_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/bd_afc3_arsw_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_rsw_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_awsw_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_wsw_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/bd_afc3_bsw_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
# IP: The module: 'design_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/bd_afc3_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_49/bd_afc3_s01a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_55/bd_afc3_s02a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_59/bd_afc3_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_65/bd_afc3_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_60/bd_afc3_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_61/bd_afc3_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_62/bd_afc3_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_63/bd_afc3_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_64/bd_afc3_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_56/bd_afc3_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_57/bd_afc3_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_58/bd_afc3_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_52/bd_afc3_s02mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_53/bd_afc3_s02tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_54/bd_afc3_s02sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_50/bd_afc3_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_51/bd_afc3_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_46/bd_afc3_s01mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_47/bd_afc3_s01tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_48/bd_afc3_s01sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/bd_afc3_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/bd_afc3_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_40/bd_afc3_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_41/bd_afc3_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_42/bd_afc3_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/bd_afc3_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/bd_afc3_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/bd_afc3_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/bd_afc3_s00a2s_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_49/bd_afc3_s01a2s_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_55/bd_afc3_s02a2s_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_59/bd_afc3_m00s2a_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_60/bd_afc3_m00arn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_61/bd_afc3_m00rn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_62/bd_afc3_m00awn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_63/bd_afc3_m00wn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_64/bd_afc3_m00bn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_56/bd_afc3_sawn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_57/bd_afc3_swn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_58/bd_afc3_sbn_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_50/bd_afc3_sarn_3_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_51/bd_afc3_srn_3_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/bd_afc3_sarn_2_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/bd_afc3_srn_2_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/bd_afc3_arsw_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_rsw_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_awsw_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_wsw_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/bd_afc3_bsw_1_ooc.xdc

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
