
####################################################################################
# Generated by Vivado 2017.1 built on 'Fri Apr 14 18:55:03 MDT 2017' by 'xbuild'
# Command Used: write_xdc ./Sources/xdc/fplan.xdc
####################################################################################


# User Generated miscellaneous constraints 

set_property HD.RECONFIGURABLE true [get_cells inst_shift]
set_property HD.RECONFIGURABLE true [get_cells inst_count]

# User Generated physical constraints 

create_pblock pblock_inst_count
add_cells_to_pblock [get_pblocks pblock_inst_count] [get_cells -quiet [list inst_count]]
resize_pblock [get_pblocks pblock_inst_count] -add {SLICE_X30Y50:SLICE_X33Y100}
resize_pblock [get_pblocks pblock_inst_count] -add {RAMB18_X2Y20:RAMB18_X2Y39}
resize_pblock [get_pblocks pblock_inst_count] -add {RAMB36_X2Y10:RAMB36_X2Y19}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_inst_count]
set_property SNAPPING_MODE ON [get_pblocks pblock_inst_count]

# User Generated miscellaneous constraints 


# User Generated physical constraints 

create_pblock pblock_inst_shift
add_cells_to_pblock [get_pblocks pblock_inst_shift] [get_cells -quiet [list inst_shift]]
resize_pblock [get_pblocks pblock_inst_shift] -add {SLICE_X98Y0:SLICE_X107Y49}
resize_pblock [get_pblocks pblock_inst_shift] -add {DSP48_X4Y0:DSP48_X4Y19}
resize_pblock [get_pblocks pblock_inst_shift] -add {RAMB18_X5Y0:RAMB18_X5Y19}
resize_pblock [get_pblocks pblock_inst_shift] -add {RAMB36_X5Y0:RAMB36_X5Y9}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_inst_shift]
set_property SNAPPING_MODE ON [get_pblocks pblock_inst_shift]

# User Generated miscellaneous constraints 


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
