# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_dma_in1_1/design_1_dma_in1_1.xci
# IP: The module: 'design_1_dma_in1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_dma_in1_1/design_1_dma_in1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dma_in1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_dma_in1_1/design_1_dma_in1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dma_in1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_dma_in1_1/design_1_dma_in1_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dma_in1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_dma_in1_1/design_1_dma_in1_1.xci
# IP: The module: 'design_1_dma_in1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_dma_in1_1/design_1_dma_in1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dma_in1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_dma_in1_1/design_1_dma_in1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dma_in1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/vivado_2017.1/DPR/PR_add_sub_int/PR_add_sub_int.srcs/sources_1/bd/design_1/ip/design_1_dma_in1_1/design_1_dma_in1_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dma_in1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
